[package]
name = "icedrop-wrapper"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
log = "0.4"
env_logger = "0.9.0"
icedrop-core = { path = "../icedrop-core" }

[build-dependencies]
cbindgen = "0.20.0"